# Generated by Django 5.0.4 on 2024-05-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(help_text='Zadej jméno alba', max_length=255),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(error_messages='Musí být zadáno jméno autora a nesmí přesahovat 255 znaků', help_text='Zadej autora', max_length=255),
        ),
    ]
