# Generated by Django 5.0.4 on 2024-05-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_album_name_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(help_text='Kdy bylo album vydáno'),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, help_text='Informace o autorovi', null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Zadej žánr', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(help_text='Zadej autora', max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(upload_to='songs'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(help_text='Zadej název skladby', max_length=255),
        ),
    ]
