# Generated by Django 5.0.4 on 2024-05-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_album_release_date_alter_author_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(error_messages='Musí být zadáno jméno autora', help_text='Zadej autora', max_length=255),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(error_messages={'max_length': 'Maximální délka je 100 znaků', 'unique': 'Žánry se nesmí opakovat'}, help_text='Zadej žánr', max_length=100, unique=True),
        ),
    ]
